name: Django Remote Server CI

on: [push]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP_ADDRESS }} << 'EOF'
            cd ${{ secrets.WORK_DIR }}
            source venv/bin/activate
            pip install -r requirements.txt
          EOF

      - name: Install migrations on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP_ADDRESS }} << 'EOF'
            cd ${{ secrets.WORK_DIR }}
            source venv/bin/activate
            python manage.py migrate
          EOF

      - name: Collect static files on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP_ADDRESS }} << 'EOF'
            cd ${{ secrets.WORK_DIR }}
            source venv/bin/activate
            python manage.py collectstatic --noinput
          EOF

      - name: Restart main application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP_ADDRESS }} << 'EOF'
            sudo systemctl restart ${{ secrets.MAIN_APPLICATION }}
          EOF
